<?php

/**
 * @file
 * Functions to remove actions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Removes the sticky/unsticky and promote/demote to home page options as they
 * are not used.
 */
function actions_remove_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (preg_match('/^views_form_content_page_[0-9]+$/', $form_id)) {
    unset($form['header']['node_bulk_form']['action']['#options']['node_make_sticky_action']);
    unset($form['header']['node_bulk_form']['action']['#options']['node_make_unsticky_action']);
    unset($form['header']['node_bulk_form']['action']['#options']['node_promote_action']);
    unset($form['header']['node_bulk_form']['action']['#options']['node_unpromote_action']);
  }
}
